# Generated by Django 6.0.7 on 2026-09-04 08:16

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contributor_user_alter_project_author_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='contributor_assigned',
            field=models.ForeignKey(default=1, on_delete=models.SET(api.models.get_or_create_anonymous_user), related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
