# Generated by Django 6.0.7 on 2026-09-08 09:28

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_issue_contributor_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='contributor_assigned',
        ),
        migrations.AddField(
            model_name='issue',
            name='user_assigned',
            field=models.ForeignKey(blank=True, default=1, on_delete=models.SET(api.models.get_or_create_anonymous_user), related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(blank=True, choices=[('bug', 'Bug'), ('task', 'Task'), ('feature', 'Feature')], max_length=20),
        ),
    ]
