# Generated by Django 6.0.7 on 2026-09-08 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_issue_contributor_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='user_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
