# Generated by Django 6.0.7 on 2026-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_contributors_project_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('back-end', 'Back End'), ('front-end', 'Front End'), ('ios', 'Ios'), ('android', 'Android')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
