# Generated by Django 6.0.7 on 2026-08-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_type_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('back-end', 'Back-end'), ('front-end', 'Front-end'), ('ios', 'iOS'), ('android', 'Android')], max_length=10),
        ),
    ]
